### ISSUE TITLE
fix your goddamned git config

### ISSUE THREAD

**Issue by ghost** [ryancarlyu/consultify#1]
![Screenshot from 2021-01-18 18-02-08](https://user-images.githubusercontent.com/1628229/104900707-5b43f680-59b7-11eb-9061-7bebbaa41c0b.png)

`Ryans-MacBook-Air.local` ain't no domain i ever heard of!
they speak English in `Ryans-MacBook-Air.local`??

**Comment by ryancarlyu** [comment]
So much love from my TM8s. LOL. Fixed!
